cmake_minimum_required(VERSION 3.29)
project(AstraRecordedBridge VERSION 0.1.0 LANGUAGES C CXX)
set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_SCAN_FOR_MODULES OFF)
set(GEODE_DISABLE_PRECOMPILED_HEADERS ON CACHE BOOL "" FORCE)
set(GEODE_DONT_USE_CCACHE ON CACHE BOOL "" FORCE)
set(GEODE_BINDINGS_REPO_PATH "${CMAKE_CURRENT_SOURCE_DIR}/../vendor/geode-bindings" CACHE PATH "" FORCE)
add_subdirectory("${CMAKE_CURRENT_SOURCE_DIR}/../vendor/geode-sdk" geode-sdk)
CPMAddPackage(NAME nlohmann_json VERSION 3.12.0 GITHUB_REPOSITORY nlohmann/json OPTIONS "JSON_BuildTests OFF")
add_library(${PROJECT_NAME} SHARED src/main.cpp)
target_link_libraries(${PROJECT_NAME} nlohmann_json::nlohmann_json)
setup_geode_mod(${PROJECT_NAME} DONT_INSTALL)
